### PR TITLE
Fixes possible SEGFAULT caused by uninitialized `external_protos`

### PR DESCRIPTION
**Pull request by bcarlson-dev**
Added additional check in `translate_device_object_to_easymesh_for_dml` to verify that `external_protos` is initialized. 

In some scenarios, the pointer to `external_protos` could be valid (not `NULL`), avoiding the first check, but the data inside the struct (including function pointers) could be `0`/`NULL`.

If uninitialized, all pointers (including pointer functions) are NULL, causing a SEGFAULT when the following `proto->get_device_info` function pointer is attempted to be called and the `proto->data_model` is attempted to be fetched.

### CODE REVIEW

**Comment by bcarlson-dev** [comment]
Okay, that has been done for this PR and my additional one

**Comment by gsathish86** [comment]
Its seems your changes  are out of sync with main. "This branch is out-of-date with the base branch"
Please resubmit the PR with latest patch codeset.

**Review by gsathish86 — APPROVED** [review]

**Comment by bcarlson-dev** [comment]
@soumyasmunshi Since you requested changes, GitHub needs your approval as well to merge

**Comment by amarnathhullur** [comment]
@bcarlson-dev, 
  Could you please raise a new PR for this change on the develop branch (if this change is required)
Thanks,
Amarnath

**Comment by bcarlson-dev** [comment]
@amarnathhullur Done. Branch has been changed to `develop`

**Pull request closed without merging**
